# -*- generated by 1.0.12 -*-
import da
PatternExpr_218 = da.pat.TuplePattern([da.pat.ConstantPattern('request'), da.pat.FreePattern('c2'), da.pat.FreePattern('p')])
PatternExpr_315 = da.pat.TuplePattern([da.pat.ConstantPattern('ack'), da.pat.FreePattern('c2'), da.pat.BoundPattern('_BoundPattern319_')])
PatternExpr_425 = da.pat.TuplePattern([da.pat.ConstantPattern('release'), da.pat.FreePattern('c'), da.pat.FreePattern('p')])
PatternExpr_493 = da.pat.TuplePattern([da.pat.ConstantPattern('done')])
PatternExpr_498 = da.pat.BoundPattern('_BoundPattern500_')
PatternExpr_501 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.BoundPattern('_BoundPattern507_')]), da.pat.TuplePattern([da.pat.ConstantPattern('done')])])
PatternExpr_600 = da.pat.TuplePattern([da.pat.ConstantPattern('done'), da.pat.BoundPattern('_BoundPattern603_')])
PatternExpr_606 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('done'), da.pat.BoundPattern('_BoundPattern616_')])])
_config_object = {'channnel': 'fifo', 'clock': 'lamport'}
import sys
import time

class P(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._PReceivedEvent_1 = []
        self._PReceivedEvent_3 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_0', PatternExpr_218, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_217]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_1', PatternExpr_315, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_2', PatternExpr_425, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_424]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_3', PatternExpr_493, sources=[PatternExpr_498], destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, s, nrequests, **rest_622):
        super().setup(s=s, nrequests=nrequests, **rest_622)
        self._state.s = s
        self._state.nrequests = nrequests
        self._state.q = set()
        self._state.timedOut = 0
        self._state.minimumTimeStamp = 100000

    def run(self):
        for i in range(self._state.nrequests):
            self.request()
            self.request()
            self.cs()
            self.release()
            self.cs()
            self.release()
        self.send(('done', self._id), to=self.parent())
        super()._label('_st_label_490', block=False)
        _st_label_490 = 0
        while (_st_label_490 == 0):
            _st_label_490 += 1
            if PatternExpr_501.match_iter(self._PReceivedEvent_3, _BoundPattern507_=self.parent(), SELF_ID=self._id):
                _st_label_490 += 1
            else:
                super()._label('_st_label_490', block=True)
                _st_label_490 -= 1
        self.output(((('Number of requests timed out for process ' + str(self._id)) + ' is :') + str(self._state.timedOut)))

    def request(self):
        c = self.logical_clock()
        self.send(('request', c, self._id), to=self._state.s)
        self._state.q.add(('request', c, self._id))

    def cs(self):
        super()._label('cs', block=False)
        self._state.minimumTimeStamp = 100000
        for (tag, c, p2) in self._state.q:
            if ((tag == 'request') and (p2 == self._id) and (c < self._state.minimumTimeStamp)):
                self._state.minimumTimeStamp = c
        c = self._state.minimumTimeStamp
        self.output(('Requesting CS with timestamp: ' + str(c)))
        super()._label('_st_label_280', block=False)
        p = c2 = None

        def UniversalOpExpr_282():
            nonlocal p, c2
            for (_ConstantPattern286_, c2, p) in self._state.q:
                if (_ConstantPattern286_ == 'request'):
                    if (not (((c2, p) == (c, self._id)) or ((c, self._id) < (c2, p)))):
                        return False
            return True
        p = c2 = None

        def UniversalOpExpr_308():
            nonlocal p, c2
            for p in self._state.s:

                def ExistentialOpExpr_313(p):
                    nonlocal c2
                    for (_, _, (_ConstantPattern330_, c2, _BoundPattern333_)) in self._PReceivedEvent_1:
                        if (_ConstantPattern330_ == 'ack'):
                            if (_BoundPattern333_ == p):
                                if (c2 > c):
                                    return True
                    return False
                if (not ExistentialOpExpr_313(p=p)):
                    return False
            return True
        _st_label_280 = 0
        self._timer_start()
        while (_st_label_280 == 0):
            _st_label_280 += 1
            if (UniversalOpExpr_282() and UniversalOpExpr_308()):
                self.output(((((('In CS of process: ' + str(self._id)) + ' with timestamp : ') + str(c)) + ' at time:') + str(self.logical_clock())))
                _st_label_280 += 1
            elif self._timer_expired:
                self._state.timedOut = (self._state.timedOut + 1)
                self.output(('Timed out for process: ' + str(self._id)))
                _st_label_280 += 1
            else:
                super()._label('_st_label_280', block=True, timeout=15)
                _st_label_280 -= 1

    def release(self):
        super()._label('release', block=False)
        for (tag, c, p) in self._state.q:
            if ((tag == 'request') and (p == self._id)):
                self._state.q.remove(('request', c, self._id))
                self.output(((((('Releasing process: ' + str(self._id)) + ' with timestamp : ') + str(c)) + ' at time:') + str(self.logical_clock())))
                self.send(('release', self.logical_clock(), self._id), to=self._state.s)
                break

    def _P_handler_217(self, c2, p):
        super()._label('receive', block=False)
        self._state.q.add(('request', c2, p))
        self.send(('ack', self.logical_clock(), self._id), to=p)
    _P_handler_217._labels = None
    _P_handler_217._notlabels = None

    def _P_handler_424(self, c, p):
        for x in {('request', c, p) for (_ConstantPattern442_, c, _BoundPattern444_) in self._state.q if (_ConstantPattern442_ == 'request') if (_BoundPattern444_ == p)}:
            self._state.q.remove(x)
            break
    _P_handler_424._labels = None
    _P_handler_424._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._Node_ReceivedEvent_0 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_Node_ReceivedEvent_0', PatternExpr_600, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[])])

    def run(self):
        nprocs = (int(sys.argv[1]) if (len(sys.argv) > 1) else 10)
        nrequests = (int(sys.argv[2]) if (len(sys.argv) > 2) else 10)
        nrequests = int((nrequests / 2))
        ps = self.new(P, num=nprocs)
        for p in ps:
            self._setup(p, ((ps - {p}), nrequests))
        self._start(ps)
        super()._label('_st_label_592', block=False)
        p = None

        def UniversalOpExpr_593():
            nonlocal p
            for p in ps:
                if (not PatternExpr_606.match_iter(self._Node_ReceivedEvent_0, _BoundPattern616_=p)):
                    return False
            return True
        _st_label_592 = 0
        while (_st_label_592 == 0):
            _st_label_592 += 1
            if UniversalOpExpr_593():
                _st_label_592 += 1
            else:
                super()._label('_st_label_592', block=True)
                _st_label_592 -= 1
        self.send(('done',), to=ps)
